<?php

namespace Samsara\Roster;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class App extends Application
{

    private const NAME = 'Roster Markdown Documentation Generator';

    public function __construct($rootDir)
    {
        $packageInfo = json_decode(file_get_contents(__DIR__.'/../../../composer.json'));

        parent::__construct(self::NAME, $packageInfo->version);

        $this->setAutoExit(false);
        $this->add(new Roster($rootDir));
    }

    public function run(InputInterface $input = null, OutputInterface $output = null)
    {
        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }

}